

import drinks from './data/drinks.json';
import history from './data/history.json';


import { WordList } from '@/interfaces';



export const PRESET_WORD_LISTS = [
  {
    name: "Urban & Industrial",
    items: [
      { word: "Scaffold", hint: "Framework" },
      { word: "Turbine", hint: "Rotation" },
      { word: "Conveyor", hint: "Movement" },
      { word: "Asphalt", hint: "Surface" },
      { word: "Pavement", hint: "Path" },
      { word: "Manhole", hint: "Access" },
      { word: "Girders", hint: "Support" },
      { word: "Hydrant", hint: "Outlet" },
      { word: "Silo", hint: "Storage" },
      { word: "Foundry", hint: "Heat" },
      { word: "Pipeline", hint: "Flow" },
      { word: "Reservoir", hint: "Capacity" },
      { word: "Grid", hint: "System" },
      { word: "Circuit", hint: "Loop" },
      { word: "Fuse", hint: "Break" },
      { word: "Relay", hint: "Pass" },
      { word: "Valve", hint: "Control" },
      { word: "Gauge", hint: "Measure" },
      { word: "Piston", hint: "Pressure" },
      { word: "Crane", hint: "Height" },
      { word: "Wrench", hint: "Torque" },
      { word: "Rivet", hint: "Fixed" },
      { word: "Vent", hint: "Exhaust" },
      { word: "Duct", hint: "Channel" },
      { word: "Vault", hint: "Secured" },
      { word: "Dock", hint: "Platform" },
      { word: "Freight", hint: "Cargo" },
      { word: "Elevator", hint: "Level" },
      { word: "Terminal", hint: "End" },
      { word: "Signal", hint: "Transmission" },
      { word: "Antenna", hint: "Reception" },
      { word: "Transformer", hint: "Conversion" },
      { word: "Engine", hint: "Power" },
      { word: "Exhaust", hint: "Waste" }
    ]
  },
  {
    name: "Cyber & Logic",
    items: [
      { word: "Firewall", hint: "Barrier" },
      { word: "Mainframe", hint: "Hub" },
      { word: "Kernel", hint: "Core" },
      { word: "Protocol", hint: "Standard" },
      { word: "Binary", hint: "Digital" },
      { word: "Encryption", hint: "Privacy" },
      { word: "Latency", hint: "Delay" },
      { word: "Packet", hint: "Unit" },
      { word: "Proxy", hint: "Intermediate" },
      { word: "Cache", hint: "Stored" },
      { word: "Gateway", hint: "Portal" },
      { word: "Bandwidth", hint: "Limit" },
      { word: "Syntax", hint: "Format" },
      { word: "Script", hint: "Automated" },
      { word: "Variable", hint: "Change" },
      { word: "Array", hint: "Sequence" },
      { word: "Boolean", hint: "States" },
      { word: "Matrix", hint: "Structure" },
      { word: "Bug", hint: "Defect" },
      { word: "Patch", hint: "Update" },
      { word: "Spam", hint: "Unwanted" },
      { word: "Pixel", hint: "Display" },
      { word: "Bit", hint: "Binary" },
      { word: "String", hint: "Data" },
      { word: "Buffer", hint: "Padding" },
      { word: "Function", hint: "Operation" },
      { word: "Port", hint: "Endpoint" },
      { word: "Server", hint: "Host" },
      { word: "Client", hint: "Remote" },
      { word: "Backdoor", hint: "Bypass" },
      { word: "Sandbox", hint: "Isolation" },
      { word: "Root", hint: "Base" },
      { word: "Hash", hint: "ID" },
      { word: "Node", hint: "Junction" }
    ]
  },
  {
    name: "Tactical & Stealth",
    items: [
      { word: "Scope", hint: "Sight" },
      { word: "Silencer", hint: "Quiet" },
      { word: "Bunker", hint: "Fortified" },
      { word: "Ambush", hint: "Surprise" },
      { word: "Patrol", hint: "Route" },
      { word: "Infil", hint: "Entry" },
      { word: "Extraction", hint: "Exit" },
      { word: "Decoy", hint: "Fake" },
      { word: "Camouflage", hint: "Blended" },
      { word: "Briefing", hint: "Intel" },
      { word: "Cipher", hint: "Code" },
      { word: "Breach", hint: "Force" },
      { word: "Sector", hint: "Zone" },
      { word: "Perimeter", hint: "Border" },
      { word: "Target", hint: "Mark" },
      { word: "Intel", hint: "Report" },
      { word: "Officer", hint: "Rank" },
      { word: "Squad", hint: "Unit" },
      { word: "Orders", hint: "Instruction" },
      { word: "Tactics", hint: "Approach" },
      { word: "Medal", hint: "Honor" },
      { word: "Radio", hint: "Comms" },
      { word: "Flare", hint: "Bright" },
      { word: "Armor", hint: "Layer" },
      { word: "Blade", hint: "Sharp" },
      { word: "Rope", hint: "Binding" },
      { word: "Vest", hint: "Protective" },
      { word: "Badge", hint: "ID" },
      { word: "Signal", hint: "Flare" },
      { word: "Base", hint: "HQ" },
      { word: "Strike", hint: "Hit" },
      { word: "Guard", hint: "Duty" },
      { word: "Agent", hint: "Active" },
      { word: "Shadow", hint: "Stealth" }
    ]
  },
  {
    name: "Scientific & Lab",
    items: [
      { word: "Catalyst", hint: "Reaction" },
      { word: "Sample", hint: "Test" },
      { word: "Isotope", hint: "Varient" },
      { word: "Flask", hint: "Container" },
      { word: "Lens", hint: "Focus" },
      { word: "Prism", hint: "Refraction" },
      { word: "Laser", hint: "Beam" },
      { word: "Vortex", hint: "Whirl" },
      { word: "Plasma", hint: "State" },
      { word: "Enzyme", hint: "Agent" },
      { word: "Formula", hint: "Logic" },
      { word: "Nucleus", hint: "Center" },
      { word: "Fusion", hint: "Union" },
      { word: "Fission", hint: "Split" },
      { word: "Element", hint: "Pure" },
      { word: "Acid", hint: "pH" },
      { word: "Base", hint: "Alkaline" },
      { word: "Crystal", hint: "Solid" },
      { word: "Vacuum", hint: "Nothing" },
      { word: "Inert", hint: "Stable" },
      { word: "Ozone", hint: "Atmosphere" },
      { word: "Nebula", hint: "Gas" },
      { word: "Orbit", hint: "Path" },
      { word: "Radiation", hint: "Emission" },
      { word: "Gravity", hint: "Pull" },
      { word: "Molecule", hint: "Bond" },
      { word: "Organism", hint: "Life" },
      { word: "Gene", hint: "Code" },
      { word: "Tissue", hint: "Cells" },
      { word: "Virus", hint: "Strain" },
      { word: "Bacteria", hint: "Growth" },
      { word: "Fossil", hint: "Preserved" },
      { word: "Stellar", hint: "Cosmic" },
      { word: "Quantum", hint: "State" }
    ]
  },
  {
    name: "Ancient & Mystical",
    items: [
      { word: "Obelisk", hint: "Stone" },
      { word: "Relic", hint: "Ancient" },
      { word: "Temple", hint: "Sanctuary" },
      { word: "Hieroglyph", hint: "Symbol" },
      { word: "Scroll", hint: "Paper" },
      { word: "Tome", hint: "Knowledge" },
      { word: "Amulet", hint: "Charm" },
      { word: "Scepter", hint: "Power" },
      { word: "Altar", hint: "Sacred" },
      { word: "Incense", hint: "Scent" },
      { word: "Oracle", hint: "Vision" },
      { word: "Rune", hint: "Script" },
      { word: "Alchemy", hint: "Lead" },
      { word: "Potions", hint: "Brew" },
      { word: "Eclipse", hint: "Shadow" },
      { word: "Zodiac", hint: "Sign" },
      { word: "Totem", hint: "Icon" },
      { word: "Mummy", hint: "Wrapped" },
      { word: "Knight", hint: "Armor" },
      { word: "Empire", hint: "Reign" },
      { word: "Shrine", hint: "Vessel" },
      { word: "Myth", hint: "Legend" },
      { word: "Prophecy", hint: "Future" },
      { word: "Cult", hint: "Following" },
      { word: "Artifact", hint: "Object" },
      { word: "Monk", hint: "Devoted" },
      { word: "Kingdom", hint: "Land" },
      { word: "Legacy", hint: "Trace" },
      { word: "Ritual", hint: "Procedure" },
      { word: "Hermit", hint: "Loner" },
      { word: "Warlock", hint: "Dark" },
      { word: "Ghost", hint: "Haunt" },
      { word: "Chant", hint: "Voice" },
      { word: "Echo", hint: "Repeat" }
    ]
  },
  {
    name: "Corporate & Finance",
    items: [
      { word: "Equity", hint: "Value" },
      { word: "Audit", hint: "Review" },
      { word: "Stocks", hint: "Market" },
      { word: "Merger", hint: "Join" },
      { word: "Fiscal", hint: "Yearly" },
      { word: "Profit", hint: "Gain" },
      { word: "Deficit", hint: "Loss" },
      { word: "Asset", hint: "Resource" },
      { word: "Broker", hint: "Middle" },
      { word: "Credit", hint: "Score" },
      { word: "Option", hint: "Choice" },
      { word: "Ledger", hint: "Record" },
      { word: "Budget", hint: "Plan" },
      { word: "Income", hint: "Flow" },
      { word: "Vendor", hint: "Seller" },
      { word: "Quota", hint: "Target" },
      { word: "Revenue", hint: "Cash" },
      { word: "Clause", hint: "Part" },
      { word: "Contract", hint: "Signed" },
      { word: "Share", hint: "Part" },
      { word: "Bonus", hint: "Extra" },
      { word: "Tax", hint: "Duty" },
      { word: "Debt", hint: "Owed" },
      { word: "Fund", hint: "Pool" },
      { word: "Crypto", hint: "Digital" },
      { word: "Bond", hint: "Agreement" },
      { word: "Scheme", hint: "Plot" },
      { word: "System", hint: "Order" },
      { word: "Markup", hint: "Price" },
      { word: "Margin", hint: "Edge" },
      { word: "Client", hint: "Target" },
      { word: "Draft", hint: "Initial" },
      { word: "Policy", hint: "Standard" },
      { word: "Brand", hint: "Label" }
    ]
  }
];

export const PRESET_WORD_LISTS_SLO = [
  {
    name: "Domače okolje",
    items: [
      { word: "Ogledalo", hint: "Odsev" },
      { word: "Ključ", hint: "Dostop" },
      { word: "Zavesa", hint: "Zakritje" },
      { word: "Preproga", hint: "Podlaga" },
      { word: "Svetilka", hint: "Sij" },
      { word: "Vaza", hint: "Vsebnik" },
      { word: "Gumb", hint: "Pritisk" },
      { word: "Daljinec", hint: "Nadzor" },
      { word: "Baterija", hint: "Vir" },
      { word: "Polnilec", hint: "Povezava" },
      { word: "Kladivo", hint: "Udarec" },
      { word: "Škarje", hint: "Rez" },
      { word: "Metla", hint: "Čiščenje" },
      { word: "Glavnik", hint: "Urejanje" },
      { word: "Milo", hint: "Pena" },
      { word: "Brisača", hint: "Vpijanje" },
      { word: "Blazina", hint: "Mehkoba" },
      { word: "Odeja", hint: "Plast" },
      { word: "Omara", hint: "Prostor" },
      { word: "Predal", hint: "Odlaganje" },
      { word: "Kljuka", hint: "Oprijem" },
      { word: "Okno", hint: "Pogled" },
      { word: "Vrata", hint: "Prehod" },
      { word: "Stopnice", hint: "Višina" },
      { word: "Stikalo", hint: "Preklop" },
      { word: "Vtičnica", hint: "Tok" },
      { word: "Koš", hint: "Odpad" },
      { word: "Ura", hint: "Ritem" },
      { word: "Koledar", hint: "Načrt" },
      { word: "Denarnica", hint: "Vsebina" },
      { word: "Torba", hint: "Nošenje" },
      { word: "Dežnik", hint: "Zaščita" },
      { word: "Očala", hint: "Fokus" },
      { word: "Nakit", hint: "Okras" }
    ]
  },
  {
    name: "Kuhinja & Hrana",
    items: [
      { word: "Vilica", hint: "Ostrina" },
      { word: "Nož", hint: "Rez" },
      { word: "Žlica", hint: "Zajem" },
      { word: "Krožnik", hint: "Krog" },
      { word: "Skodelica", hint: "Rob" },
      { word: "Lonec", hint: "Volumen" },
      { word: "Ponev", hint: "Ploskev" },
      { word: "Pečica", hint: "Vročina" },
      { word: "Hladilnik", hint: "Svežina" },
      { word: "Tehtnica", hint: "Mera" },
      { word: "Cedilo", hint: "Prehod" },
      { word: "Lijak", hint: "Odtok" },
      { word: "Poper", hint: "Začimba" },
      { word: "Sol", hint: "Okus" },
      { word: "Sladkor", hint: "Sladkost" },
      { word: "Olje", hint: "Mast" },
      { word: "Kis", hint: "Kislost" },
      { word: "Moka", hint: "Prah" },
      { word: "Testenine", hint: "Oblika" },
      { word: "Riž", hint: "Zrno" },
      { word: "Kruh", hint: "Sredica" },
      { word: "Maslo", hint: "Mazanje" },
      { word: "Mleko", hint: "Bela" },
      { word: "Jajce", hint: "Lupina" },
      { word: "Čaj", hint: "Napitek" },
      { word: "Kava", hint: "Vonj" },
      { word: "Sok", hint: "Sadje" },
      { word: "Voda", hint: "Osnova" },
      { word: "Med", hint: "Gostota" },
      { word: "Sir", hint: "Zrelost" },
      { word: "Krompir", hint: "Plod" },
      { word: "Solata", hint: "List" },
      { word: "Sadje", hint: "Narava" },
      { word: "Sladoled", hint: "Mraz" }
    ]
  },
  {
    name: "Zunaj & Mesto",
    items: [
      { word: "Avto", hint: "Pogon" },
      { word: "Kolo", hint: "Vrtenje" },
      { word: "Avtobus", hint: "Skupina" },
      { word: "Vlak", hint: "Tirnica" },
      { word: "Semafor", hint: "Barva" },
      { word: "Cesta", hint: "Smer" },
      { word: "Most", hint: "Povezava" },
      { word: "Trg", hint: "Odprtost" },
      { word: "Park", hint: "Zeleno" },
      { word: "Klop", hint: "Počitek" },
      { word: "Fontana", hint: "Pršenje" },
      { word: "Kip", hint: "Figura" },
      { word: "Trgovina", hint: "Ponudba" },
      { word: "Lekarna", hint: "Pomoč" },
      { word: "Pošta", hint: "Dostava" },
      { word: "Banka", hint: "Varnost" },
      { word: "Kino", hint: "Zaslon" },
      { word: "Gledališče", hint: "Nastop" },
      { word: "Šola", hint: "Učenje" },
      { word: "Bolnica", hint: "Zdravje" },
      { word: "Cerkev", hint: "Stolp" },
      { word: "Grad", hint: "Zgodovina" },
      { word: "Muzej", hint: "Zbirka" },
      { word: "Garaža", hint: "Zavetje" },
      { word: "Ograja", hint: "Meja" },
      { word: "Pločnik", hint: "Hod" },
      { word: "Ulica", hint: "Naslov" },
      { word: "Stadion", hint: "Navijanje" },
      { word: "Bencinska", hint: "Gorivo" },
      { word: "Gostilna", hint: "Druženje" },
      { word: "Kiosk", hint: "Obrobje" },
      { word: "Hotel", hint: "Bivanje" },
      { word: "Letališče", hint: "Vzlet" },
      { word: "Pristanišče", hint: "Ladja" }
    ]
  },
  {
    name: "Narava & Čas",
    items: [
      { word: "Sonce", hint: "Toplina" },
      { word: "Luna", hint: "Noč" },
      { word: "Zvezda", hint: "Točka" },
      { word: "Oblak", hint: "Siva" },
      { word: "Dež", hint: "Kaplje" },
      { word: "Sneg", hint: "Bela" },
      { word: "Veter", hint: "Premik" },
      { word: "Megla", hint: "Vidljivost" },
      { word: "Nevihta", hint: "Hrup" },
      { word: "Gora", hint: "Vrh" },
      { word: "Hrib", hint: "Vzpon" },
      { word: "Dolina", hint: "Dno" },
      { word: "Gozd", hint: "Drevesa" },
      { word: "Reka", hint: "Tok" },
      { word: "Jezero", hint: "Mir" },
      { word: "Morje", hint: "Obzorje" },
      { word: "Otok", hint: "Samota" },
      { word: "Plaža", hint: "Pesek" },
      { word: "Travnik", hint: "Cvetje" },
      { word: "Vrt", hint: "Gojenje" },
      { word: "Drevo", hint: "Korenine" },
      { word: "Grm", hint: "Gostota" },
      { word: "Kamen", hint: "Trdota" },
      { word: "Zemlja", hint: "Tla" },
      { word: "Trava", hint: "Zelena" },
      { word: "List", hint: "Ploskev" },
      { word: "Cvet", hint: "Barva" },
      { word: "Plod", hint: "Hrana" },
      { word: "Pomlad", hint: "Prebujanje" },
      { word: "Poletje", hint: "Vročina" },
      { word: "Jesen", hint: "Barve" },
      { word: "Zima", hint: "Mraz" },
      { word: "Jutro", hint: "Svit" },
      { word: "Večer", hint: "Mrak" }
    ]
  },
  {
    name: "Zabava & Hobi",
    items: [
      { word: "Knjiga", hint: "Zgodba" },
      { word: "Revija", hint: "Listanje" },
      { word: "Telefon", hint: "Zaslon" },
      { word: "Računalnik", hint: "Tipkanje" },
      { word: "Televizija", hint: "Program" },
      { word: "Radio", hint: "Zvok" },
      { word: "Glasba", hint: "Melodija" },
      { word: "Film", hint: "Slika" },
      { word: "Igra", hint: "Pravila" },
      { word: "Žoga", hint: "Odboj" },
      { word: "Karte", hint: "Mešanje" },
      { word: "Kocke", hint: "Sestava" },
      { word: "Puzzle", hint: "Deli" },
      { word: "Barvice", hint: "Sledi" },
      { word: "Fotoaparat", hint: "Spomin" },
      { word: "Kitaro", hint: "Strune" },
      { word: "Klavir", hint: "Tipke" },
      { word: "Ples", hint: "Gibanje" },
      { word: "Šport", hint: "Ekipa" },
      { word: "Tek", hint: "Tempo" },
      { word: "Plavanje", hint: "Voda" },
      { word: "Smučanje", hint: "Drsenje" },
      { word: "Pohodništvo", hint: "Pot" },
      { word: "Kuhanje", hint: "Priprava" },
      { word: "Vrtnarjenje", hint: "Rast" },
      { word: "Ribolov", hint: "Čakanje" },
      { word: "Kampiranje", hint: "Šotor" },
      { word: "Potovanje", hint: "Sprememba" },
      { word: "Zabava", hint: "Vzdušje" },
      { word: "Darilo", hint: "Presenečenje" },
      { word: "Praznik", hint: "Tradicija" },
      { word: "Koncert", hint: "Nastop" },
      { word: "Piknik", hint: "Odeja" },
      { word: "Kolo", hint: "Vožnja" }
    ]
  },
  {
    name: "Osebe & Telo",
    items: [
      { word: "Glava", hint: "Zgoraj" },
      { word: "Roka", hint: "Doseg" },
      { word: "Noga", hint: "Korak" },
      { word: "Oči", hint: "Pogled" },
      { word: "Usta", hint: "Glas" },
      { word: "Ušesa", hint: "Zvok" },
      { word: "Nos", hint: "Vonj" },
      { word: "Srce", hint: "Utrip" },
      { word: "Lasje", hint: "Gostota" },
      { word: "Prst", hint: "Dotik" },
      { word: "Hrbet", hint: "Zadaj" },
      { word: "Obraz", hint: "Izraz" },
      { word: "Koža", hint: "Površina" },
      { word: "Kri", hint: "Rdeča" },
      { word: "Spanje", hint: "Počitek" },
      { word: "Smeh", hint: "Veselje" },
      { word: "Solza", hint: "Vlaga" },
      { word: "Glas", hint: "Sporočilo" },
      { word: "Ime", hint: "Oznaka" },
      { word: "Družina", hint: "Skupnost" },
      { word: "Prijatelj", hint: "Zaupanje" },
      { word: "Sosed", hint: "Bližina" },
      { word: "Otrok", hint: "Majhnost" },
      { word: "Človek", hint: "Bitje" },
      { word: "Zdravnik", hint: "Pregled" },
      { word: "Učitelj", hint: "Prenos" },
      { word: "Kuhar", hint: "Okus" },
      { word: "Prodajalec", hint: "Izmenjava" },
      { word: "Voznik", hint: "Premik" },
      { word: "Policist", hint: "Red" }
    ]
  },
  {
    name: "Oblačila & Stil",
    items: [
      { word: "Čevelj", hint: "Podplat" },
      { word: "Nogavica", hint: "Par" },
      { word: "Hlače", hint: "Hlačnica" },
      { word: "Majica", hint: "Rokav" },
      { word: "Jopica", hint: "Zadrga" },
      { word: "Jakna", hint: "Plast" },
      { word: "Kapa", hint: "Pokrivalo" },
      { word: "Rokavice", hint: "Prsti" },
      { word: "Šal", hint: "Vrat" },
      { word: "Pas", hint: "Sponka" },
      { word: "Obleka", hint: "Kroj" },
      { word: "Krilo", hint: "Rob" },
      { word: "Pižama", hint: "Spanje" },
      { word: "Žep", hint: "Odprtina" },
      { word: "Gumb", hint: "Zapora" },
      { word: "Ovratnik", hint: "Vrat" },
      { word: "Podloga", hint: "Notranjost" },
      { word: "Vzorec", hint: "Izgled" }
    ]
  },
  {
    name: "Pisarna & Šola",
    items: [
      { word: "Svinčnik", hint: "Sled" },
      { word: "Nalivnik", hint: "Črnilo" },
      { word: "Radirka", hint: "Popravek" },
      { word: "Zvezek", hint: "Listanje" },
      { word: "Mapa", hint: "Vložek" },
      { word: "Sponka", hint: "Zveza" },
      { word: "Lepilo", hint: "Stik" },
      { word: "Ravnalo", hint: "Črta" },
      { word: "Šiljček", hint: "Ostrina" },
      { word: "Tiskalnik", hint: "Izpis" },
      { word: "Zaslon", hint: "Slika" },
      { word: "Tipkovnica", hint: "Vnos" },
      { word: "Miška", hint: "Klik" },
      { word: "Miza", hint: "Ploskev" },
      { word: "Stol", hint: "Naslon" },
      { word: "Tabla", hint: "Pisanje" },
      { word: "Kreda", hint: "Prah" },
      { word: "Torba", hint: "Naramnica" }
    ]
  },
  {
    name: "Kopalnica & Higiena",
    items: [
      { word: "Ščetka", hint: "Ščetine" },
      { word: "Pasta", hint: "Svežina" },
      { word: "Britvica", hint: "Rez" },
      { word: "Glavnik", hint: "Zobje" },
      { word: "Šampon", hint: "Pena" },
      { word: "Gel", hint: "Mazilo" },
      { word: "Parfum", hint: "Vonj" },
      { word: "Vatirana palčka", hint: "Uho" },
      { word: "Pila", hint: "Brušenje" },
      { word: "Lak", hint: "Barva" },
      { word: "Krema", hint: "Nanos" },
      { word: "Tuš", hint: "Pršenje" },
      { word: "Kad", hint: "Voda" },
      { word: "Pipa", hint: "Curek" },
      { word: "Školjka", hint: "Sedalo" },
      { word: "Papir", hint: "Rola" },
      { word: "Goba", hint: "Vpijanje" },
      { word: "Piling", hint: "Zrna" }
    ]
  },
  {
    name: "Elektronika & Naprave",
    items: [
      { word: "Zvočnik", hint: "Membrana" },
      { word: "Slušalke", hint: "Uho" },
      { word: "Kamera", hint: "Leča" },
      { word: "Bliskavica", hint: "Svetloba" },
      { word: "Antena", hint: "Sprejem" },
      { word: "Kabel", hint: "Žica" },
      { word: "Vtikač", hint: "Kontakt" },
      { word: "Baterija", hint: "Shranjevanje" },
      { word: "Ekran", hint: "Dotik" },
      { word: "Čip", hint: "Logika" },
      { word: "Hladilnik", hint: "Ventilator" },
      { word: "Stikalo", hint: "Pritisk" },
      { word: "Senzor", hint: "Zaznava" },
      { word: "Žarnica", hint: "Nitka" },
      { word: "Daljinec", hint: "Infrardeče" },
      { word: "Modem", hint: "Povezava" }
    ]
  },
  {
    name: "Ulica & Transport",
    items: [
      { word: "Volan", hint: "Smer" },
      { word: "Guma", hint: "Profil" },
      { word: "Pedal", hint: "Noga" },
      { word: "Menjalnik", hint: "Prestava" },
      { word: "Sedež", hint: "Pas" },
      { word: "Smernik", hint: "Utripanje" },
      { word: "Motor", hint: "Hrup" },
      { word: "Izpuh", hint: "Dim" },
      { word: "Registracija", hint: "Tablica" },
      { word: "Križišče", hint: "Srečanje" },
      { word: "Krožišče", hint: "Krog" },
      { word: "Pločnik", hint: "Rob" },
      { word: "Steza", hint: "Smučka" },
      { word: "Peron", hint: "Postaja" },
      { word: "Tir", hint: "Kovina" },
      { word: "Kabina", hint: "Voznik" }
    ]
  },
  {
    name: "Čutila & Občutki",
    items: [
      { word: "Glasba", hint: "Uho" },
      { word: "Slika", hint: "Oko" },
      { word: "Vonj", hint: "Nos" },
      { word: "Okus", hint: "Jezik" },
      { word: "Dotik", hint: "Prst" },
      { word: "Bolečina", hint: "Signal" },
      { word: "Mraz", hint: "Tresenje" },
      { word: "Vročina", hint: "Pot" },
      { word: "Žeja", hint: "Grlo" },
      { word: "Lakota", hint: "Trebuh" },
      { word: "Strah", hint: "Srce" },
      { word: "Sreča", hint: "Obraz" },
      { word: "Spanec", hint: "Veke" },
      { word: "Umetnost", hint: "Izraz" },
      { word: "Hrup", hint: "Glasnost" },
      { word: "Tišina", hint: "Mir" }
    ]
  }
];

export const ALL_DATA = {
  en: PRESET_WORD_LISTS,     
  sl: PRESET_WORD_LISTS_SLO,  
};