spring.application.name=imposter-backend
spring.datasource.url=${PG_URL}
spring.datasource.username=${PG_USER}
spring.datasource.password=${PG_PASS}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=86400000
logging.level.org.hibernate.SQL=DEBUG

springdoc.group-config[0].group=v1
springdoc.group-config[0].paths-to-match=/api/v1/**

spring.config.import=optional:file:.env[.properties]