spring.application.name=imposter-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/imposterdb
spring.datasource.username=postgres
spring.datasource.password=PgPass1
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

app.jwt.secret=NGNhZjE4Yzg5M2YzNDI3MmI0YmZmMmU4YjAyYjA1ZDEyYjU0ZGM2YjE5YzI4NjcwYjJiZGY0N2MyY2Y5NGRl
app.jwt.expiration-ms=86400000
logging.level.org.hibernate.SQL=DEBUG